<?php

class SayacTipSeeder extends Seeder {

	public function run()
	{
        SayacTip::create([
            'sayacmarka_id'=>1,
            'sayactur_id'=>1,
            'tipadi'=>'ÖN ÖDEMELİ'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>1,
            'sayactur_id'=>1,
            'tipadi'=>'ÖN ÖDEMESİZ'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>1,
            'sayactur_id'=>1,
            'tipadi'=>'MEKANİK'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>1,
            'sayactur_id'=>1,
            'tipadi'=>'PARÇA'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>1,
            'sayactur_id'=>2,
            'tipadi'=>'ÖN ÖDEMELİ'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>1,
            'sayactur_id'=>2,
            'tipadi'=>'ÖN ÖDEMESİZ'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>1,
            'sayactur_id'=>2,
            'tipadi'=>'PARÇA'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>2,
            'sayactur_id'=>3,
            'tipadi'=>'ÖN ÖDEMELİ'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>2,
            'sayactur_id'=>5,
            'tipadi'=>'DİYAFRAM'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>2,
            'sayactur_id'=>5,
            'tipadi'=>'ROTARY'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>2,
            'sayactur_id'=>5,
            'tipadi'=>'TURBIN'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>2,
            'sayactur_id'=>5,
            'tipadi'=>'QUANTOMETRE'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>4,
            'sayactur_id'=>5,
            'tipadi'=>'DİYAFRAM'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>4,
            'sayactur_id'=>5,
            'tipadi'=>'ROTARY'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>4,
            'sayactur_id'=>5,
            'tipadi'=>'TURBIN'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>4,
            'sayactur_id'=>5,
            'tipadi'=>'QUANTOMETRE'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>3,
            'sayactur_id'=>5,
            'tipadi'=>'DİYAFRAM'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>3,
            'sayactur_id'=>5,
            'tipadi'=>'ROTARY'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>3,
            'sayactur_id'=>5,
            'tipadi'=>'TURBIN'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>3,
            'sayactur_id'=>5,
            'tipadi'=>'QUANTOMETRE'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>8,
            'sayactur_id'=>5,
            'tipadi'=>'DİYAFRAM'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>5,
            'sayactur_id'=>5,
            'tipadi'=>'DİYAFRAM'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>6,
            'sayactur_id'=>5,
            'tipadi'=>'ROTARY'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>6,
            'sayactur_id'=>5,
            'tipadi'=>'TURBIN'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>6,
            'sayactur_id'=>5,
            'tipadi'=>'QUANTOMETRE'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>12,
            'sayactur_id'=>5,
            'tipadi'=>'ROTARY'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>12,
            'sayactur_id'=>5,
            'tipadi'=>'TURBIN'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>12,
            'sayactur_id'=>5,
            'tipadi'=>'QUANTOMETRE'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>7,
            'sayactur_id'=>5,
            'tipadi'=>'ROTARY'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>7,
            'sayactur_id'=>5,
            'tipadi'=>'TURBIN'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>7,
            'sayactur_id'=>5,
            'tipadi'=>'QUANTOMETRE'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>4,
            'sayactur_id'=>3,
            'tipadi'=>'ÖN ÖDEMELİ'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>3,
            'sayactur_id'=>3,
            'tipadi'=>'ÖN ÖDEMELİ'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>8,
            'sayactur_id'=>3,
            'tipadi'=>'ÖN ÖDEMELİ'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>5,
            'sayactur_id'=>3,
            'tipadi'=>'ÖN ÖDEMELİ'
        ]);
        SayacTip::create([
            'sayacmarka_id'=>1,
            'sayactur_id'=>3,
            'tipadi'=>'ÖN ÖDEMELİ'
        ]);
	}

}
